### ISSUE TITLE
Actions not being fired

### ISSUE THREAD

**Issue by celicoo** [scoutforpets/ember-fullcalendar#3] opened 2015-12-08 04:06 UTC
Hei again Jason, how are you?

I'm having some trouble with the actions. I'm defining the action "clicked" exactly as you teach in the docs, but nothing happens.

So, i was testing this other plugin -> https://github.com/icicletech/ember-cli-full-calendar and i don't need change anything to make it work, but i prefer this one, since has support for pt-BR language.

I also try clone the repo and test, but I was not able to make it work. Do you have any idea why is not working?

Thanks again!

**Comment by jamesdixon** [comment] 2015-12-08 04:08
Hello - can you provide a code example?

**Comment by celicoo** [comment] 2015-12-08 04:08
Hei, you are really fast! Give me a sec haha.

**Comment by jamesdixon** [comment] 2015-12-08 04:33
Hi - honestly can't say I see anything wrong with the code. Have you set a breakpoint on the line of your `alert`? I'm also using `eventClick` with an action and it works fine.

**Comment by celicoo** [comment] 2015-12-08 04:38
No. I was using my own css and i set some classes as pointer-events: none, but i commented all and i'm using the default one now.

I also updated my ember from 1.13.8 to 1.13.9.

**Comment by jamesdixon** [comment] 2015-12-08 04:40
I think you may have misunderstood -- what I meant by breakpoint was related to debugging your code using something like Chrome Dev Tools.

**Comment by celicoo** [comment] 2015-12-08 04:42
Oh.. sorry.

Let my try this.

**Comment by celicoo** [comment] 2015-12-08 04:57
@jamesdixon I added a breakpoint in the alert line, and still nothing happens when i click in the event :/

**Comment by celicoo** [comment] 2015-12-08 05:04
That's my package.json:

```json
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-bootstrap-datetimepicker": "1.0.2",
    "ember-cli": "^1.13.8",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-cors": "0.0.1",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-filter-by-query": "1.1.3",
    "ember-cli-html5-validation": "0.0.*",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment-shim": "0.7.1",
    "ember-cli-notifications": "2.1.3",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.0",
    "ember-cli-simple-auth": "^0.8.0",
    "ember-cli-simple-auth-token": "^0.7.3",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.8",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-fullcalendar": "0.0.3",
    "ember-invoke-action": "1.2.0",
    "ember-moment": "4.1.0",
    "ember-new-computed": "1.0.3",
    "ember-tooltips": "0.5.4",
    "ember-truth-helpers": "1.2.0"
  }
```

**Comment by jamesdixon** [comment] 2015-12-08 17:11
@celicoo can you try and reproduce this in a clean Ember app? If you can reproduce it there, publish it to Github and I can pull it down and take a look. As of now, I cannot reproduce this on my end.

**Comment by celicoo** [comment] 2015-12-09 03:27
@jamesdixon of course I can. I shall return in three days then, okay? I 'm implementing another part of the application now.

**Comment by jamesdixon** [comment] 2015-12-09 06:22
@celicoo sounds good!

**Comment by jamesdixon** [comment] 2015-12-16 06:51
@celicoo going to close this for now. If you are able to reproduce the issue, please reopen. Thanks!

**Closed by jamesdixon** 2015-12-16 06:51 UTC
Labels: question
